dataset_configs:
  dataset_name: "satoshidg/GSM-MC-Stage"
  data_files: "test.csv"
  split: "train"
  max_samples: 5

model_configs:
  model_name: "nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1"
  allowed_choices: []
