[project]
name = "llm-bias-fairness-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "pytest>=8.3.5",
    "streamlit>=1.45.1",
    "transformers>=4.52.3",
]
