dataset_configs:
  dataset_name: "satoshidg/GSM-MC-Stage"
  data_files: "test.csv"
  split: "train"
  max_samples: 4

model_configs:
  model_name: "nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1"
  allowed_choices: []
  batch_size: 2
  tokenizer_padding_side: "left"

artifact_configs:
  artifacts_root: "artifacts"
  predictions_folder_path: "artifacts/predictions.csv"
  mlflow_run_id: 7e352ab615974977b383fc60749bad7b
